### ISSUE TITLE
Swift ? Really ?

### ISSUE THREAD

**Issue by kaiyes** [EQuimper/ios11-tutorials#1]
LoL. after RN, you are turning into swift ? 😄  😄  😄  😄  😄  😄  😄  

I mean, I understand you working on phoenix/elixir etc, but Swift ? 🙈 🙈 🙈 🙈

**Comment by EQuimper** [comment]
@kaiyes I need some tips for learning augmented reality. And also I need to make native module at the job sometime. After swift I go with kotlin, this is not for get a job but improve rn. :)

**Comment by kaiyes** [comment]
Awesome.  I heard good stuff about kotlin. May be after React native I will dive into Kotlin as well

**Comment by EQuimper** [comment]
@kaiyes Yes it's just good to have basic knowledge of native if you go deep in rn. I see that in 2 of my last project where we ask native coder to help me :s
